# Generated by Django 2.1.7 on 2019-06-27 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberCaclModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insuredValue', models.CharField(max_length=13)),
                ('policyFee', models.CharField(max_length=13)),
                ('premiumFee', models.CharField(default='10', max_length=13)),
                ('total', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='MembersModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberName', models.CharField(max_length=13)),
                ('member_id', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='NonMemberCalcModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='UserIdModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_id', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='UserNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterName', models.CharField(max_length=13)),
            ],
        ),
        migrations.AddField(
            model_name='nonmembercalcmodel',
            name='nonMemberName',
            field=models.OneToOneField(on_delete=None, to='calc_app.UserNameModel'),
        ),
        migrations.AddField(
            model_name='nonmembercalcmodel',
            name='nonMember_id',
            field=models.OneToOneField(on_delete=None, to='calc_app.UserIdModel'),
        ),
        migrations.AddField(
            model_name='membercaclmodel',
            name='memberName',
            field=models.OneToOneField(default=1, on_delete=None, to='calc_app.UserNameModel'),
        ),
        migrations.AddField(
            model_name='membercaclmodel',
            name='member_id',
            field=models.OneToOneField(default=1, on_delete=None, to='calc_app.UserIdModel'),
        ),
    ]
