# Generated by Django 2.1.7 on 2019-06-27 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercaclmodel',
            name='memberName',
            field=models.OneToOneField(default=0, on_delete=None, to='calc_app.UserNameModel'),
        ),
        migrations.AlterField(
            model_name='membercaclmodel',
            name='member_id',
            field=models.OneToOneField(default=0, on_delete=None, to='calc_app.UserIdModel'),
        ),
    ]
