# Generated by Django 2.1.7 on 2019-07-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0005_auto_20190627_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmembercalcmodel',
            name='nonMemberName',
            field=models.OneToOneField(default=0, on_delete=None, to='calc_app.UserNameModel'),
        ),
        migrations.AlterField(
            model_name='nonmembercalcmodel',
            name='nonMember_id',
            field=models.OneToOneField(default=0, on_delete=None, to='calc_app.UserIdModel'),
        ),
    ]
