# Generated by Django 2.1.7 on 2019-07-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0006_auto_20190701_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonmembercalcmodel',
            name='nonMemberName',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='nonmembercalcmodel',
            name='nonMember_id',
            field=models.CharField(max_length=13),
        ),
    ]
