# Generated by Django 2.1.7 on 2019-07-02 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc_app', '0007_auto_20190701_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membercaclmodel',
            name='memberName',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='membercaclmodel',
            name='member_id',
            field=models.CharField(max_length=13),
        ),
    ]
